# This is a basic workflow to help you get started with Actions

name: Test

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - uses: JasonEtco/rss-to-readme@v1
          with:
            feed-url: https://sahansera.dev/rss.xml
            readme-section: feed
            max: 5 # max number of items (default 5)
